language: csharp

env:
  global:
    - EnableNuGetPackageRestore=true
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "kC7O0CWm9h4g+tzCwhIZEGwcdiLrb1/1PijeOKGbIWGuWS7cIksAkj2tRNMgtxxcE9CFQr8W7xDv2YzflCIlqN1nGkFjbyD4CrNg6+V1j0fZjPOQ6ssdBBVPrfrvecsAUJ0/48Tqa9VTkEpZSlwOF/VS1sO2ob36FVyWjtxvG9s="

git:
  # we need recursive init
  submodules: false

cache: apt

solution: CatchAllAgent.sln

script:
- xbuild CatchAllAgent.sln /p:Configuration="Ex2007 SP3"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2010"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2010 SP1"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2010 SP2"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2010 SP3"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013 CU1"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013 CU2"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013 CU3"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013 SP1 CU4"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013 SP1 CU5"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013 SP1 CU6"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013 SP1 CU7"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013 SP1 CU8"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013 SP1 CU9"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2013 SP1 CU10"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2016 Preview"
- xbuild CatchAllAgent.sln /p:Configuration="Ex2016 RTM"
- xbuild CatchAllAgent.sln /p:Configuration="Release"